# Generated by Django 5.1.4 on 2025-01-04 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpsession',
            name='mobile_number',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='otpsession',
            name='otp_sent',
            field=models.CharField(max_length=255),
        ),
    ]
