# Generated by Django 5.1.4 on 2025-01-04 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_otpsession_mobile_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpsession',
            name='otp_sent',
            field=models.CharField(max_length=4),
        ),
    ]
