# Generated by Django 5.1.4 on 2025-03-20 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_otplog_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpsession',
            name='otp_sent',
            field=models.CharField(max_length=4),
        ),
    ]
