# Generated by Django 5.1.4 on 2025-01-04 09:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_otpsession_otp_sent'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mobile_number', models.CharField(max_length=255)),
                ('otp_sent', models.CharField(max_length=6)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device_os', models.CharField(blank=True, max_length=50, null=True)),
                ('browser', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='otpsession',
            name='browser',
        ),
        migrations.RemoveField(
            model_name='otpsession',
            name='device_os',
        ),
        migrations.RemoveField(
            model_name='otpsession',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='otpsession',
            name='region',
        ),
        migrations.AddField(
            model_name='otpsession',
            name='otp_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='authentication.otplog'),
        ),
    ]
