# Generated by Django 5.1.4 on 2025-03-20 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_otpsession_otp_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otplog',
            name='sent_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
