# Generated by Django 5.1.4 on 2025-01-04 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_otplog_remove_otpsession_browser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otplog',
            name='otp_sent',
            field=models.CharField(max_length=4),
        ),
    ]
