# Generated by Django 5.1.4 on 2025-01-04 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_otplog_otp_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otplog',
            name='browser',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='otplog',
            name='region',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
