# Generated by Django 5.1.4 on 2025-01-07 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpsession',
            name='log_status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Open'), (1, 'Success'), (2, 'Logged Out')], default=0),
        ),
    ]
