# Generated by Django 5.1.4 on 2025-03-03 07:02

import django.core.validators
import lorryledger.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lorryledger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='aadhar_number',
            field=models.CharField(default='000000000000', max_length=12, validators=[django.core.validators.RegexValidator(message='Aadhar number must be exactly 12 digits.', regex='^\\d{12}$')]),
        ),
        migrations.AddField(
            model_name='driver',
            name='documents',
            field=models.FileField(blank=True, null=True, upload_to=lorryledger.models.driver_document_upload_path),
        ),
        migrations.AddField(
            model_name='driver',
            name='license_expiry_date',
            field=models.DateField(default='2025-01-01'),
        ),
        migrations.AddField(
            model_name='driver',
            name='license_number',
            field=models.CharField(default='DL-NOT-SET', max_length=20),
        ),
        migrations.AddField(
            model_name='driver',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=lorryledger.models.driver_photo_upload_path),
        ),
    ]
