# Generated by Django 5.1.4 on 2025-03-24 13:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lorryledger', '0002_driver_aadhar_number_driver_documents_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(validators=[django.core.validators.RegexValidator(message='Amount should contain only number', regex='^\\d$')])),
                ('amountType', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], default='credit', max_length=20)),
                ('reason', models.CharField(max_length=35)),
                ('date', models.DateField(default='2025-01-01')),
                ('driverId', models.CharField()),
            ],
        ),
    ]
