# Generated by Django 5.1.4 on 2025-03-24 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lorryledger', '0003_transactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='amountType',
            field=models.CharField(choices=[('Debit', 'Debit'), ('Credit', 'Credit')], default='Credit', max_length=20),
        ),
    ]
