# Generated by Django 5.1.4 on 2025-03-24 13:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lorryledger', '0004_alter_transactions_amounttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='amount',
            field=models.CharField(validators=[django.core.validators.RegexValidator(message='Amount should contain only number', regex='^\\d*$')]),
        ),
    ]
