# Generated by Django 5.1.4 on 2025-04-02 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lorryledger', '0005_alter_transactions_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truckNo', models.CharField(max_length=10)),
                ('truckType', models.CharField(choices=[('Mini Truck / LCV', 'Mini Truck / LCV'), ('Opend Body Truck', 'Open Body Truck'), ('Closed Container', 'Closed Container'), ('Trailer', 'Trailer'), ('Tanker', 'Tanker'), ('Tipper', 'Tipper'), ('Other', 'Other')], default='Tanker')),
                ('ownership', models.CharField(choices=[('Market Truck', 'Market Truck'), ('My Truck', 'My Truck')], default='My Truck')),
                ('truckStatus', models.CharField(choices=[('available', 'Available'), ('on_trip', 'On Trip'), ('off_duty', 'Off Duty')], default='available', max_length=20)),
            ],
        ),
    ]
