# Generated by Django 5.1.4 on 2025-04-02 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lorryledger', '0006_truck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='truckType',
            field=models.CharField(choices=[('Mini Truck / LCV', 'Mini Truck / LCV'), ('Open Body Truck', 'Open Body Truck'), ('Closed Container', 'Closed Container'), ('Trailer', 'Trailer'), ('Tanker', 'Tanker'), ('Tipper', 'Tipper'), ('Other', 'Other')], default='Tanker'),
        ),
    ]
