# Generated by Django 5.1.4 on 2025-04-07 15:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lorryledger', '0007_alter_truck_trucktype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truckId', models.CharField()),
                ('expenseType', models.CharField(choices=[('Showroom Service', 'Showroom Service'), ('Regular Service', 'Regular Service'), ('Minor Repair', 'Minor Repair'), ('Gear Maintenance', 'Gear Maintenance'), ('Brake Oil Change', 'Brake Oil Change'), ('Grease Oil Change', 'Grease Oil Change'), ('Engine Oil Change', 'Engine Oil Change'), ('Spare Parts Purhcase', 'Spare Parts Purhcase'), ('Air Filter Change', 'Air Filter Change'), ('Tyre Purchase', 'Tyre Purchase'), ('Tyre Retread', 'Tyre Retread'), ('Tyre Puncture', 'Tyre Puncture'), ('Roof Top Repair', 'Roof Top Repair'), ('Driver Batta', 'Driver Batta'), ('Driver Payment', 'Driver Payment'), ('Loading Charges', 'Loading Charges'), ('Unloading Charges', 'Unloading Charges'), ('Detention Charges', 'Detention Charges'), ('Union Charges', 'Union Charges'), ('Toll Expense', 'Toll Expense'), ('Police Expense', 'Police Expense'), ('RTO Expense', 'RTO Expense'), ('Brokerage Expense', 'Brokerage Expense'), ('Other Expense', 'Other Expense'), ('Fuel Expense', 'Fuel Expense')])),
                ('amountPaid', models.CharField(validators=[django.core.validators.RegexValidator(message='Amount should contain only number', regex='^\\d*$')])),
                ('expenseDate', models.DateField(default='2025-01-01')),
                ('paymentMode', models.CharField(choices=[('Cash', 'Cash'), ('Credit', 'Credit'), ('Paid by Driver', 'Paid by Driver'), ('Online', 'Online')], default='Cash')),
                ('currentKmReading', models.CharField(validators=[django.core.validators.RegexValidator(message='Reading should contain only number', regex='^\\d*$')])),
                ('fuelQuantity', models.CharField(validators=[django.core.validators.RegexValidator(message='Quantity should contain only number', regex='^\\d*$')])),
            ],
        ),
    ]
