# Generated by Django 5.1.4 on 2025-04-07 15:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lorryledger', '0008_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='fuelQuantity',
            field=models.CharField(blank=True, validators=[django.core.validators.RegexValidator(message='Quantity should contain only number', regex='^\\d*$')]),
        ),
    ]
