# Generated by Django 5.1.4 on 2025-04-07 17:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lorryledger', '0009_alter_expense_fuelquantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='currentKmReading',
            field=models.CharField(blank=True, validators=[django.core.validators.RegexValidator(message='Reading should contain only number', regex='^\\d*$')]),
        ),
    ]
