# Generated by Django 5.1.4 on 2025-04-07 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lorryledger', '0010_alter_expense_currentkmreading'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='notes',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
