# Generated by Django 5.1.4 on 2025-04-18 12:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lorryledger', '0013_supplier_alter_party_pincode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('partyBillingType', models.CharField(choices=[('Fixed', 'Fixed'), ('Per Tonne', 'Per Tonne'), ('Per Kg', 'Per Kg'), ('Per Km', 'Per Km'), ('Per Trip', 'Per Trip'), ('Per Day', 'Per Day'), ('Per Hour', 'Per Hour'), ('Per Litre', 'Per Litre'), ('Per Bag', 'Per Bag')])),
                ('partyFreightAmount', models.CharField(validators=[django.core.validators.RegexValidator(message='Amount must be in digits.', regex='^\\d$')])),
                ('startDate', models.DateField(default='2025-01-01')),
                ('startKmsReading', models.CharField(blank=True, validators=[django.core.validators.RegexValidator(message='Reading should contain only number', regex='^\\d*$')])),
                ('partyId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='lorryledger.party')),
                ('truckId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='lorryledger.truck')),
            ],
        ),
    ]
