# Generated by Django 5.1.4 on 2025-04-18 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lorryledger', '0014_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='tripStatus',
            field=models.CharField(choices=[('Started', 'Started'), ('Completed', 'Completed'), ('POD Received', 'POD Received'), ('POD Submitted', 'POD Submitted'), ('Settled', 'Settled')], default='Started'),
        ),
    ]
