# Generated by Django 5.1.4 on 2025-04-18 12:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lorryledger', '0015_trip_tripstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='partyFreightAmount',
            field=models.CharField(validators=[django.core.validators.RegexValidator(message='Amount must be in digits.', regex='^\\d+$')]),
        ),
    ]
