# Generated by Django 5.1.4 on 2025-04-19 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lorryledger', '0017_trip_driverid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='driverId',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='lorryledger.driver'),
        ),
    ]
