# Generated by Django 5.1.4 on 2025-04-22 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lorryledger', '0020_lr'),
    ]

    operations = [
        migrations.AddField(
            model_name='lr',
            name='tripId',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, related_name='LR', to='lorryledger.trip'),
        ),
    ]
