# Generated by Django 5.1.4 on 2025-04-30 04:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lorryledger', '0021_lr_tripid'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='LRCount',
            field=models.CharField(blank=True, default=0, validators=[django.core.validators.RegexValidator(message='Amount must be in digits.', regex='^\\d+$')]),
        ),
        migrations.AddField(
            model_name='trip',
            name='PODReceivedDate',
            field=models.DateField(blank=True, default='2025-01-01'),
        ),
        migrations.AddField(
            model_name='trip',
            name='PODSubmittedDate',
            field=models.DateField(blank=True, default='2025-01-01'),
        ),
        migrations.AddField(
            model_name='trip',
            name='endKmsReading',
            field=models.CharField(blank=True, validators=[django.core.validators.RegexValidator(message='Reading should contain only number', regex='^\\d*$')]),
        ),
        migrations.AddField(
            model_name='trip',
            name='receivedByDriver',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trip',
            name='settlementDate',
            field=models.DateField(blank=True, default='2025-01-01'),
        ),
        migrations.AddField(
            model_name='trip',
            name='settlementNotes',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='trip',
            name='settlementPaymentMode',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Cheque', 'Cheque'), ('UPI', 'UPI'), ('Bank Transfer', 'Bank Transfer'), ('Fuel', 'Fuel'), ('Others', 'Others')], default='Cash'),
        ),
        migrations.AddField(
            model_name='trip',
            name='tripEndDate',
            field=models.DateField(blank=True, default='2025-01-01'),
        ),
    ]
