# Generated by Django 5.1.4 on 2025-04-30 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lorryledger', '0022_trip_lrcount_trip_podreceiveddate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='PODReceivedDate',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='PODSubmittedDate',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='settlementDate',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='tripEndDate',
            field=models.DateField(blank=True),
        ),
    ]
