# Generated by Django 5.1.4 on 2025-05-06 07:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lorryledger', '0024_alter_trip_podreceiveddate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='LRCount',
        ),
        migrations.AddField(
            model_name='trip',
            name='noOfUnits',
            field=models.CharField(default=0, validators=[django.core.validators.RegexValidator(message='Number of Units must be in digits.', regex='^\\d+$')]),
        ),
        migrations.AddField(
            model_name='trip',
            name='ratePerUnit',
            field=models.CharField(default=0, validators=[django.core.validators.RegexValidator(message='Rate must be in digits.', regex='^\\d+$')]),
        ),
        migrations.AddField(
            model_name='trip',
            name='routes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
