# Generated by Django 5.1.4 on 2025-05-06 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lorryledger', '0025_remove_trip_lrcount_trip_noofunits_trip_rateperunit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='tripType',
            field=models.CharField(choices=[('Single Route', 'Single Route'), ('Multiple Routes', 'Multiple Routes')], default='Single Route'),
        ),
    ]
