# Generated by Django 5.1.4 on 2025-05-09 09:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lorryledger', '0026_trip_triptype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='partyFreightAmount',
            field=models.CharField(validators=[django.core.validators.RegexValidator(message='Amount must be in digits.', regex='^\\d+(\\.\\d+)?$')]),
        ),
        migrations.AlterField(
            model_name='trip',
            name='ratePerUnit',
            field=models.CharField(default=0, validators=[django.core.validators.RegexValidator(message='Rate must be in digits.', regex='^\\d+(\\.\\d+)?$')]),
        ),
    ]
