# Generated by Django 5.1.4 on 2025-05-14 18:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lorryledger', '0027_alter_trip_partyfreightamount_alter_trip_rateperunit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freightPaidBy', models.CharField(choices=[('Consigner', 'Consigner'), ('Consignee', 'Consignee'), ('Agent', 'Agent')], default='Consigner')),
                ('gstPercentage', models.CharField(blank=True, max_length=3, validators=[django.core.validators.RegexValidator(message='Percentage must be within 100.', regex='^\\d*$')])),
                ('invoiceDate', models.DateField(default='2025-01-01')),
                ('invoiceNumber', models.CharField(max_length=30)),
                ('materialCategory', models.CharField(max_length=50)),
                ('numberOfPackages', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Number of Packages should be a number', regex='^\\d*$')])),
                ('unit', models.CharField(choices=[('Tonnes', 'Tonnes'), ('Kg', 'Kg'), ('Quintal', 'Quintal')], default='Tonnes')),
                ('weight', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='Weight must be a number', regex='^\\d*$')])),
                ('consigneeId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Invoice', to='lorryledger.consignee')),
                ('consignerId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Invoice', to='lorryledger.consigner')),
                ('tripId', models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, related_name='Invoice', to='lorryledger.trip')),
            ],
        ),
    ]
