# Generated by Django 5.1.4 on 2025-05-22 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lorryledger', '0028_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='expenses',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
