# Generated by Django 5.1.4 on 2025-05-27 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lorryledger', '0029_trip_expenses'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='advances',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='trip',
            name='charges',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='trip',
            name='payments',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
