# Generated by Django 5.1.4 on 2025-05-28 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lorryledger', '0030_trip_advances_trip_charges_trip_payments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='advances',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='charges',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='expenses',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='payments',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
