# Generated by Django 5.1.4 on 2025-06-15 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lorryledger', '0031_alter_trip_advances_alter_trip_charges_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='documents',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
