# Generated by Django 5.1.4 on 2025-06-16 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lorryledger', '0032_truck_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='emi',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
