# Generated by Django 5.1.4 on 2025-06-18 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lorryledger', '0033_truck_emi'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='last_document_reminder_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='last_emi_reminder_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
