# Generated by Django 5.1.4 on 2025-06-24 14:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lorryledger', '0037_alter_lr_numberofpackages_alter_lr_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='numberOfPackages',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Number of Packages should be a number', regex='^\\d*$')]),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='weight',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.RegexValidator(message='Weight must be a number', regex='^\\d*$')]),
        ),
    ]
