# Generated by Django 5.1.4 on 2025-06-25 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lorryledger', '0038_alter_invoice_numberofpackages_alter_invoice_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='routeIndex',
            field=models.CharField(default=-1, max_length=30),
        ),
        migrations.AddField(
            model_name='lr',
            name='routeIndex',
            field=models.CharField(default=-1, max_length=30),
        ),
    ]
